title: Bhangmeter V2
logo: /assets/img/logo.png
description: Host for the Bhangmeter V2 project
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
sass:
  style: compressed
  sourcemap: never